import { Link } from "react-router-dom";
import { Navbar } from "../components";

export const AdmPrizePage = () => {
  return (
    <>
      <Navbar />
      <br />
      <br />
      <div className="container-fluid">
        <div>
          CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO
          CAMILO CAMILO CAMILO CAMILO CAMILO <br />
          CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO
          CAMILO CAMILO CAMILO CAMILO CAMILO <br />
          CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO
          CAMILO CAMILO CAMILO CAMILO CAMILO <br />
          CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO
          CAMILO CAMILO CAMILO CAMILO CAMILO <br />
          CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO
          CAMILO CAMILO CAMILO CAMILO CAMILO <br />
          CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO
          CAMILO CAMILO CAMILO CAMILO CAMILO <br />
          CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO
          CAMILO CAMILO CAMILO CAMILO CAMILO <br />
          CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO
          CAMILO CAMILO CAMILO CAMILO CAMILO <br />
          CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO
          CAMILO CAMILO CAMILO CAMILO CAMILO <br />
          CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO CAMILO
          CAMILO CAMILO CAMILO CAMILO CAMILO <br />
          AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA
          AYUDA AYUDA AYUDA AYUDA <br />
          AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA
          AYUDA AYUDA AYUDA AYUDA <br />
          AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA
          AYUDA AYUDA AYUDA AYUDA <br />
          AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA
          AYUDA AYUDA AYUDA AYUDA <br />
          AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA
          AYUDA AYUDA AYUDA AYUDA <br />
          AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA
          AYUDA AYUDA AYUDA AYUDA <br />
          AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA
          AYUDA AYUDA AYUDA AYUDA <br />
          AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA
          AYUDA AYUDA AYUDA AYUDA <br />
          AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA
          AYUDA AYUDA AYUDA AYUDA <br />
          AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA
          AYUDA AYUDA AYUDA AYUDA <br />
          AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA AYUDA
          AYUDA AYUDA AYUDA AYUDA <br />
          PORFA PORFA PORFA PORFA PORFA PORFA PORFA PORFA PORFA PORFA PORFA
          PORFA PORFA PORFA PORFA <br />
          PORFA PORFA PORFA PORFA PORFA PORFA PORFA PORFA PORFA PORFA PORFA
          PORFA PORFA PORFA PORFA <br />
          PORFA PORFA PORFA PORFA PORFA PORFA PORFA PORFA PORFA PORFA PORFA
          PORFA PORFA PORFA PORFA <br />
        </div>
        <br />
        <Link
          to="/createPrize"
          className="btn btn-primary green-btn"
          style={{ width: "100%" }}
        >
          Crear premio
        </Link>
      </div>
    </>
  );
};
