export * from "./LoginPage";
export * from "./HomePage";
export * from "./RegisterPage";
export * from "./EventListPage";
export * from "./AdmEmpPage";
export * from "./ProfileEmpPage";
export * from "./RankListPage";
export * from "./ProfilePage";
export * from "./AdmColaboradoresPage.tsx"
